#数据库连接
spring: 

    datasource: 
        url: jdbc:mysql://localhost:3306/hydropower_sys?serverTimezone=UTC
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    mybatis:
        typeAliasesPackage: com.panglin.pojo
        mapperLocations: classpath:mapper/*.xml
    mvc:
        view:
          prefix: resources/
          suffix: .html

#服务器端口
server:
  port: 8080